version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=http://localhost:3001
      - VITE_SOCKET_URL=http://localhost:3001
    command: npm run dev -- --host 0.0.0.0

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
      - "9229:9229"  # Node.js debugging port
    volumes:
      - ./server/src:/app/src
      - ./shared:/app/shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:5173
    command: npm run dev