#!/bin/bash

echo "🚀 GitHub Push Helper for Korean Mafia Game"
echo "=========================================="
echo ""
echo "Repository: https://github.com/JihunKong/classroom-mafia"
echo ""
echo "현재 커밋 상태:"
git log --oneline -5
echo ""
echo "준비된 파일들:"
echo "- Client (React): $(find client/src -name "*.tsx" -o -name "*.ts" | wc -l) 파일"
echo "- Server (Node.js): $(find server/src -name "*.ts" | wc -l) 파일"
echo "- Docker 설정: ✅"
echo "- Railway 설정: ✅"
echo ""
echo "GitHub에 푸시하려면 다음 명령어를 실행하세요:"
echo ""
echo "git push -u origin main"
echo ""
echo "인증 정보 입력:"
echo "- Username: JihunKong"
echo "- Password: [GitHub Personal Access Token]"
echo ""
echo "토큰이 없다면:"
echo "1. https://github.com/settings/tokens 접속"
echo "2. 'Generate new token (classic)' 클릭"
echo "3. 'repo' 권한 체크"
echo "4. 생성된 토큰을 비밀번호로 사용"
echo ""
echo "푸시 후 Railway 환경변수 설정이 필요합니다."