[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build && ls -la server/dist/"

[deploy]
startCommand = "cd server && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "korean-mafia-game"
port = 3001