#!/bin/bash

echo "🔒 안전한 GitHub 푸시 가이드"
echo "============================"
echo ""
echo "⚠️  중요: Personal Access Token이 노출되었습니다!"
echo "보안을 위해 다음 단계를 따라주세요:"
echo ""
echo "1. 즉시 GitHub에서 이 토큰을 폐기하세요:"
echo "   https://github.com/settings/tokens"
echo ""
echo "2. 새 토큰을 생성하세요:"
echo "   - 'Generate new token (classic)' 클릭"
echo "   - 'repo' 권한만 체크"
echo "   - 짧은 만료 기간 설정 권장"
echo ""
echo "3. 터미널에서 직접 푸시하세요:"
echo "   git push -u origin main"
echo ""
echo "4. Username: JihunKong"
echo "5. Password: [새로 생성한 토큰]"
echo ""
echo "💡 팁: 토큰은 절대 채팅이나 파일에 입력하지 마세요!"